### ISSUE TITLE
xdotool: freezes the OS

### ISSUE THREAD

**Issue by 52617365** [ideasman42/nerd-dictation#51] opened 2022-04-17 14:51 UTC
When I run the program by assigning the command "nerd-dictation begin --timeout 1 --numbers-as-digits --numbers-use-separator"
to a custom Keyboard Shortcut on Ubuntu 20.04 it seems to be freezing every single time. Any fixes for this?
It seems to behave like a memory leak, It completely crashes the OS.

**Comment by 52617365** [comment] 2022-04-17 15:13
My setup is 
Processor: AMD Ryzen 7 5800X 8-Core Processor
GPU: Nvidia Geforce Gtx 1050ti
32gb of 3200 mhz ddr4 ram

**Comment by ideasman42** [comment] 2022-04-18 07:22
Firstly, I'm not sure this is something that can be "fixed" on our side.
If the system is freezing, that seems like a bad configuration that allows a single process to freeze the entire system.

Could you try one of the smaller language models? I suspect some of the larger models could cause excessive overhead.

Although your system should easily be good enough to support dictation, that's where I'd start looking.

**Comment by 52617365** [comment] 2022-04-20 19:42
> 
There is no fancy configurations on my side, all I've done is attach the python script into a keybinding in the Ubuntu built in keyboard settings. Do you suggest I make a bash script and call that instead? I agree that my system could and should easily handle this.

Also, thanks for the suggestion, I will test it out with a smaller model.

**Comment by Philetjosie** [comment] 2022-04-24 13:19
Hello, I have the same problem, and after many tests, it seems the problem comes from xdotool and not from nerd-dictation or vosk. However, i have not found a way to correct it for now. You can see a previous issue aimed at running nerd-dictation with wayland, that involves to replace xdotool by ydotool. It should solve this problem in the same time. I did a trial, by editing nerd-dictation and replacing xdotool by ydotool. It does not freeze anymore. However, there are two other problems: error messages saying that I need to have ydotoold (even after installing it), and worse, the word are displayed probably without taking into account my keyboard or language. For example, when I say «bonjour», with xdotool I get «bonjour» but with ydotool, I get «kl'tlvo» which is pretty strange (but same number of letters, so a keyboard matching error probably).
So I'm now waiting for the next release of nerd-dictation, officially supporting ydotool (or something else) and I hope i will solve these freezing issue.

**Comment by ideasman42** [comment] 2022-05-06 00:07
Can we narrow this down to a spesific configuration?

**Comment by NathanLovato** [comment] 2022-05-13 19:48
I had the same problem, looked it up and found this bug report on xdotool: https://github.com/jordansissel/xdotool/issues/10

When some keyboard layouts, like US alt. international, writing a single line of text with xdotool can take 15 seconds. Seems the issue has to do with the X server itself. I can confirm that ydotool doesn't suffer from this. Making a PR that should fix this now.

**Comment by NathanLovato** [comment] 2022-05-16 08:13
I would recommend trying again using ydotool, it's now supported by nerd-dictation. That may solve the problem entirely: https://github.com/ideasman42/nerd-dictation/blob/master/readme-ydotool.rst

**Comment by ideasman42** [comment] 2022-05-16 12:14
Thanks Nathan for working on ydotool support, while it's a bit of work to setup it works very well.

I'm going to close this report as it's not something we can fix on our side and there is a way to workaround the problem.

**Closed by ideasman42** 2022-05-16 12:14 UTC

**Comment by lm2lm2** [comment] 2023-05-12 11:50
> I would recommend trying again using ydotool, it's now supported by nerd-dictation. That may solve the problem entirely: https://github.com/ideasman42/nerd-dictation/blob/master/readme-ydotool.rst

hello
Im a long time user of xdotool, very satisfied until using it on some webforms, through chrome/iridium/firefox : after few hours, xdotool makes the browser crash. Im using in background anydesk and nomachine. 
however, I tried several times the ydotool alternative, until ydotoold was root-started : 
ydotoold: listening on socket /tmp/.ydotool_socket
ydotoold: accepted client
Erreur de segmentation [segmentation fault] (core dumped)

since this (reported last week on their project git), I have no idea to do, and I mostly see that Im far of it not the only one to get stuck by a core dumped/segfault. I dont know where does it comes, Im running it on LMDE5 fresh install, Id like to get xdotool or ydotool running well (please notice Im still with xorg), but to get a program whom crashes at almost every commands (just did one or two " ydotool key 56:1 62:1 62:0 56:0 ydotool: notice: ydotoold backend unavailable (may have latency+delay issues)" commands in terminal to have it crashed makes me a bit misunderstanding if Im supposed to go on that new software.

And in fact, I just dont know how to solve this..
